from __future__ import annotations

from vtnote.schemas import TranscriptSegment
from vtnote.subtitles import (
    export_ass,
    export_markdown,
    export_srt,
    export_txt,
    export_vtt,
    parse_ass,
    parse_srt,
    parse_vtt,
)


def test_parse_srt_multiline_cues_and_millisecond_timestamps() -> None:
    source = """1
00:00:01,250 --> 00:00:03,500
First line
second line

2
00:00:04.000 --> 00:00:05.100
Last cue
"""

    assert parse_srt(source) == [
        TranscriptSegment(
            id="segment-000001",
            start_ms=1_250,
            end_ms=3_500,
            text="First line\nsecond line",
        ),
        TranscriptSegment(
            id="segment-000002",
            start_ms=4_000,
            end_ms=5_100,
            text="Last cue",
        ),
    ]


def test_parse_vtt_ignores_metadata_and_cue_settings() -> None:
    source = """WEBVTT Example

NOTE generated by a subtitle service
not a cue

intro
00:00:01.000 --> 00:00:02.500 align:start position:10%
Hello
world

00:02.500 --> 00:04.000
Goodbye
"""

    assert parse_vtt(source) == [
        TranscriptSegment(
            id="segment-000001",
            start_ms=1_000,
            end_ms=2_500,
            text="Hello\nworld",
        ),
        TranscriptSegment(
            id="segment-000002",
            start_ms=2_500,
            end_ms=4_000,
            text="Goodbye",
        ),
    ]


def test_parse_ass_uses_event_format_and_normalizes_ass_text() -> None:
    source = """[Script Info]
Title: Example

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.20,0:00:03.40,Default,Alice,0,0,0,,{\\i1}Hello{\\i0}\\Nworld
Dialogue: 0,0:00:04.00,0:00:05.50,Default,Bob,0,0,0,,A comma, stays here
"""

    assert parse_ass(source) == [
        TranscriptSegment(
            id="segment-000001",
            start_ms=1_200,
            end_ms=3_400,
            speaker="Alice",
            text="Hello\nworld",
        ),
        TranscriptSegment(
            id="segment-000002",
            start_ms=4_000,
            end_ms=5_500,
            speaker="Bob",
            text="A comma, stays here",
        ),
    ]


def test_srt_export_is_stable_after_round_trip() -> None:
    cues = [
        TranscriptSegment(id="a", start_ms=1_001, end_ms=2_345, text="Hello\nworld"),
        TranscriptSegment(id="b", start_ms=3_000, end_ms=4_000, text="Goodbye"),
    ]

    rendered = export_srt(cues)

    assert export_srt(parse_srt(rendered)) == rendered


def test_vtt_export_is_stable_after_round_trip() -> None:
    cues = [
        TranscriptSegment(id="a", start_ms=1_001, end_ms=2_345, text="Hello\nworld"),
        TranscriptSegment(id="b", start_ms=3_000, end_ms=4_000, text="Goodbye"),
    ]

    rendered = export_vtt(cues)

    assert export_vtt(parse_vtt(rendered)) == rendered


def test_ass_export_is_stable_after_round_trip() -> None:
    cues = [
        TranscriptSegment(
            id="a",
            start_ms=1_200,
            end_ms=2_340,
            text="Hello\nworld",
            speaker="Alice",
        )
    ]

    rendered = export_ass(cues)

    assert export_ass(parse_ass(rendered)) == rendered


def test_plain_text_and_markdown_exports_are_deterministic() -> None:
    cues = [
        TranscriptSegment(id="a", start_ms=1_000, end_ms=2_000, text="Hello"),
        TranscriptSegment(id="b", start_ms=3_000, end_ms=4_000, text="Goodbye"),
    ]

    assert export_txt(cues) == "Hello\nGoodbye\n"
    assert export_markdown(cues) == (
        "- **00:00:01.000 → 00:00:02.000** Hello\n"
        "- **00:00:03.000 → 00:00:04.000** Goodbye\n"
    )
