from __future__ import annotations

import pytest

from vtnote.schemas import TranscriptSegment
from vtnote.subtitles import (
    SubtitleExportError,
    export_ass,
    export_markdown,
    export_srt,
    export_txt,
    export_vtt,
    parse_ass,
    parse_srt,
    parse_vtt,
)


def test_parse_srt_multiline_cues_and_millisecond_timestamps() -> None:
    source = """1
00:00:01,250 --> 00:00:03,500
First line
second line

2
00:00:04.000 --> 00:00:05.100
Last cue
"""

    assert parse_srt(source) == [
        TranscriptSegment(
            id="seg_000001",
            start_ms=1_250,
            end_ms=3_500,
            text="First line\nsecond line",
        ),
        TranscriptSegment(
            id="seg_000002",
            start_ms=4_000,
            end_ms=5_100,
            text="Last cue",
        ),
    ]


def test_parse_vtt_ignores_metadata_and_cue_settings() -> None:
    source = """WEBVTT Example

NOTE generated by a subtitle service
not a cue

intro
00:00:01.000 --> 00:00:02.500 align:start position:10%
Hello
world

00:02.500 --> 00:04.000
Goodbye
"""

    assert parse_vtt(source) == [
        TranscriptSegment(
            id="seg_000001",
            start_ms=1_000,
            end_ms=2_500,
            text="Hello\nworld",
        ),
        TranscriptSegment(
            id="seg_000002",
            start_ms=2_500,
            end_ms=4_000,
            text="Goodbye",
        ),
    ]


def test_parse_ass_uses_event_format_and_normalizes_ass_text() -> None:
    source = """[Script Info]
Title: Example

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.20,0:00:03.40,Default,Alice,0,0,0,,{\\i1}Hello{\\i0}\\Nworld
Dialogue: 0,0:00:04.00,0:00:05.50,Default,Bob,0,0,0,,A comma, stays here
"""

    assert parse_ass(source) == [
        TranscriptSegment(
            id="seg_000001",
            start_ms=1_200,
            end_ms=3_400,
            text="Hello\nworld",
        ),
        TranscriptSegment(
            id="seg_000002",
            start_ms=4_000,
            end_ms=5_500,
            text="A comma, stays here",
        ),
    ]


def test_srt_export_is_stable_after_round_trip() -> None:
    cues = [
        TranscriptSegment(id="seg_000001", start_ms=1_001, end_ms=2_345, text="Hello\nworld"),
        TranscriptSegment(id="seg_000002", start_ms=3_000, end_ms=4_000, text="Goodbye"),
    ]

    rendered = export_srt(cues)

    assert export_srt(parse_srt(rendered)) == rendered


def test_vtt_export_is_stable_after_round_trip() -> None:
    cues = [
        TranscriptSegment(id="seg_000001", start_ms=1_001, end_ms=2_345, text="Hello\nworld"),
        TranscriptSegment(id="seg_000002", start_ms=3_000, end_ms=4_000, text="Goodbye"),
    ]

    rendered = export_vtt(cues)

    assert export_vtt(parse_vtt(rendered)) == rendered


def test_ass_export_is_stable_after_round_trip() -> None:
    cues = [
        TranscriptSegment(
            id="seg_000001",
            start_ms=1_200,
            end_ms=2_340,
            text="Hello\nworld",
        )
    ]

    rendered = export_ass(cues)

    assert export_ass(parse_ass(rendered)) == rendered


def test_plain_text_and_markdown_exports_are_deterministic() -> None:
    cues = [
        TranscriptSegment(id="seg_000001", start_ms=1_000, end_ms=2_000, text="Hello"),
        TranscriptSegment(id="seg_000002", start_ms=3_000, end_ms=4_000, text="Goodbye"),
    ]

    assert export_txt(cues) == "Hello\nGoodbye\n"
    assert export_markdown(cues) == (
        "- **00:00:01.000 → 00:00:02.000** Hello\n"
        "- **00:00:03.000 → 00:00:04.000** Goodbye\n"
    )


@pytest.mark.parametrize("exporter", [export_srt, export_vtt])
def test_srt_and_vtt_exports_reject_internal_blank_lines(exporter) -> None:
    segment = TranscriptSegment(
        id="seg_000001",
        start_ms=0,
        end_ms=1_000,
        text="first line\n\nsecond line",
    )

    with pytest.raises(SubtitleExportError, match="blank line"):
        exporter([segment])


def test_ass_export_rejects_a_range_that_quantizes_to_zero_duration() -> None:
    segment = TranscriptSegment(
        id="seg_000001",
        start_ms=1,
        end_ms=9,
        text="too short",
    )

    with pytest.raises(SubtitleExportError, match="centisecond"):
        export_ass([segment])


def test_ass_export_preserves_override_like_literal_text_stably() -> None:
    segment = TranscriptSegment(
        id="seg_000001",
        start_ms=1_000,
        end_ms=2_000,
        text=r"{\i1}\N literal, not styling",
    )

    rendered = export_ass([segment])
    parsed = parse_ass(rendered)

    assert parsed[0].text == segment.text
    assert export_ass(parsed) == rendered
